import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>holomem randomizer</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:site_name" content="holomem randomizer"></meta>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hello world!</h1>
      </main>
    </div>
  );
}
