import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>holomem randomizer</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:site_name" content="holomem randomizer"></meta>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Randomizer</h1>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  // Calls Holodex's API endpoint to get hololive members
  const res = await fetch(
    "https://holodex.net/api/v2/channels?org=Hololive&limit=100&sort=suborg&offset=4&type=vtuber"
  );
  const data = await res.json();

  // By returning { props: { data } }, the component
  // will receive `data` as a prop at build time
  return {
    props: {
      data,
    },
  };
}
